### ISSUE TITLE
Error when parsing SDP answer

### ISSUE THREAD

**Issue by tobiasfriden** [jlaine/aiortc#114]
After upgrading to version `0.9.14`, I am getting the following error when parsing the recieved SDP answer: 
```
Traceback (most recent call last):
  File "error.py", line 45, in <module>
    loop.run_until_complete(error())
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "error.py", line 41, in error
    await pc.setRemoteDescription(RTCSessionDescription(sdp=sdp, type="answer"))
  File "/Users/tobiasfriden/airpelago/dmc-webrtc/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py", line 528, in setRemoteDescription
    ssrc=media.ssrc[0].ssrc,
IndexError: list index out of range
```
Reverting back go `0.9.13` everything works fine.
Minimal example code to reproduce:
```python
import asyncio
from aiortc import RTCPeerConnection, RTCSessionDescription
from aiortc.contrib.media import MediaPlayer

# Received SDP
sdp = """v=0
o=- 3754725498 3754725498 IN IP4 3.121.248.224
s=VideoRoom 1234
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS janus
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 3.121.248.224
a=recvonly
a=mid:0
a=rtcp-mux
a=ice-ufrag:Mfwz
a=ice-pwd:sPfYombZXNeZn1c5gpHZ27
a=ice-options:trickle
a=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38
a=setup:active
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=candidate:1 1 udp 2013266431 3.121.248.224 10174 typ host
a=candidate:2 1 udp 1677722111 3.121.248.224 10174 typ srflx raddr 172.18.0.2 rport 10174
a=end-of-candidates
"""

async def error():
    player = MediaPlayer("video.m4v")
    track = player.video

    pc = RTCPeerConnection()
    pc.addTrack(track)
    await pc.setLocalDescription(await pc.createOffer())

    await pc.setRemoteDescription(RTCSessionDescription(sdp=sdp, type="answer"))

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(error())
```

**Comment by jlaine** [comment]
Ok indeed the code will fail if we don't know the remote SSRC.. I'll go back to the drawing board..

**Comment by tobiasfriden** [comment]
Yeah I guess so unfortunately.. 
Since it works on `0.9.13`, what was changed since then?
It seems like Janus does not add the SSRC to the sdp-answer for some reason.. since in my case there is only one track, could it by default use that one if there is no SSRC in the answer?

**Comment by tobiasfriden** [comment]
Great!
I use this docker setup, it works good out of the box: https://github.com/linagora/docker-janus-gateway

**Comment by jlaine** [comment]
OK, thanks for the tips, I'll see if I can get round to firing up Janus. In the meantime could you comment on whether the latest commit fixes this issue (and likewise for #112)?

**Comment by tobiasfriden** [comment]
Both this and #112 work fine with the latest version, thanks a lot for the quick help!

**Comment by jlaine** [comment]
You're welcome, it's good to have actionable issues which clearly describe the usecase  + problem + the relevant SDP.

**Comment by jlaine** [comment]
I have pushed out aiortc 0.9.15 which contains both fixes
