### ISSUE TITLE
[RTCRtpSender] Packet sequence_number overflow

### ISSUE THREAD

**Issue by dsvictor94** [jlaine/aiortc#16]
Hi, I did a long running test and after some time the eventloop stops when tries to pack a packet to send.

I suspect that it is becouse the sequence_number is never reseted and overflow the unsigned short 'H' 

I will reexecute with debug enable this night and return with more detail.

I can fork and fix this, if the spec allow jump to zero when overflow.

```
Task exception was never retrieved
future: <Task finished coro=<RTCRtpSender._run() done, defined at /home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtcrtpsender.py:78> exception=error("'H' format requires 0 <= number <= 65535",)>
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtcrtpsender.py", line 97, in _run
    await self.transport._send_rtp(bytes(packet))
  File "/home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtp.py", line 138, in __bytes__
    self.ssrc)
struct.error: 'H' format requires 0 <= number <= 65535
Task exception was never retrieved
future: <Task finished coro=<RTCRtpSender._run() done, defined at /home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtcrtpsender.py:78> exception=error("'H' format requires 0 <= number <= 65535",)>
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtcrtpsender.py", line 97, in _run
    await self.transport._send_rtp(bytes(packet))
  File "/home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtp.py", line 138, in __bytes__
    self.ssrc)
struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by jlaine** [comment]
Good catch.. this definitely needs fixing

**Comment by dsvictor94** [comment]
I did the test again with debug and confirm the overflow

```
DEBUG:rtp:sender(video) > RtpPacket(seq=65534, ts=53904, marker=0, payload=97, 1300 bytes)
DEBUG:ice:Connection(0) protocol(19) > ('192.168.0.107', 53784) DATA 1322
DEBUG:rtp:sender(video) > RtpPacket(seq=65535, ts=53904, marker=1, payload=97, 343 bytes)
DEBUG:ice:Connection(0) protocol(19) > ('192.168.0.107', 53784) DATA 365
DEBUG:rtp:sender(video) > RtpPacket(seq=65536, ts=53905, marker=1, payload=97, 1250 bytes)
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<RTCRtpSender._run() done, defined at /home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtcrtpsender.py:78> exception=error("'H' format requires 0 <= number <= 65535",)>
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtcrtpsender.py", line 97, in _run
    await self.transport._send_rtp(bytes(packet))
  File "/home/victor/.pyenv/versions/pfcount/lib/python3.5/site-packages/aiortc/rtp.py", line 138, in __bytes__
    self.ssrc)
struct.error: 'H' format requires 0 <= number <= 65535
```

reading the RTP RFC (https://tools.ietf.org/html/rfc3550#section-9.1) I not found a explicite action to do on overflow, but at page 79 the verification seems to validate seq that wrappers around

> After a source is considered valid, the sequence number is considered
   valid if it is no more than MAX_DROPOUT ahead of s->max_seq nor more
   than MAX_MISORDER behind.  If the new sequence number is ahead of
   max_seq modulo the RTP sequence number range (16 bits), but is
   smaller than max_seq, it has wrapped around and the (shifted) count
   of sequence number cycles is incremented.  A value of one is returned
   to indicate a valid sequence number.

I will try to fix it and send a pull request
