### ISSUE TITLE
How to fix delay in conversations

### ISSUE THREAD

**Issue by sogand145** [jlaine/aiortc#24]
Hi Jlaine, how are you?
First of all thanks a lot for writing this great module
we are using it for a conversation between two users, but when playing voice of second user for first user and vice versa, we have delay about less than 2 seconds and during the conversation this delay 
 increases.
How can I fix this issue?
Please let me know why you are using `pause` function in your codes?

The code we changed : 

```
import argparse
import asyncio
import json
import logging
import os
import time
import wave

from aiohttp import web
import aiortc
from aiortc import RTCPeerConnection, RTCSessionDescription
from aiortc.mediastreams import (AudioFrame, AudioStreamTrack, VideoFrame,
                                 VideoStreamTrack)

import psycopg2
import hashlib

DB_details = {"db":"db_name",
               "user": "usr_name",
               "pass":"password",
               "host":"localhost",
               "port":"5432"
            }

connect_str = "dbname={} user={} host={} port={} password={}".format(DB_details["db"],
                                                                    DB_details["user"],
                                                                    DB_details["host"],
                                                                    DB_details["port"],
                                                                    DB_details["pass"])

ROOT = os.path.dirname(__file__)

rtc_io = {
    'call-1': {
        '1': {
            'audio': [],
            'video': [],
            'connected': False
        },
        '2': {
            'audio': [],
            'video': [],
            'connected': False
        }
    }
}




def md5(input_string):
    return hashlib.md5(input_string.encode('utf-8')).hexdigest()

async def pause(last, ptime):
    if last:
        now = time.time()
        await asyncio.sleep(last + ptime - now)
    return time.time()


class AudioFileTrack(AudioStreamTrack):
    def __init__(self, path):
        self.last = None
        self.reader = wave.Wave_read(path)

    async def recv(self):
        self.last = await pause(self.last, 0.02)
        return AudioFrame(
            channels=self.reader.getnchannels(),
            data=self.reader.readframes(160),
            sample_rate=self.reader.getframerate())


class AudioRemoteTrack(AudioStreamTrack):
    def __init__(self, call_id, remote_id):
        self.last = None
        self.call_id = call_id

        print("remote id ",remote_id)
        self.remote_id = remote_id
        self.default_frame = AudioFrame(channels=1, data=b'\x00\x00' * 160, sample_rate=8000)

    async def recv(self):
        self.last = await pause(self.last, 0.02)
        if rtc_io[self.call_id][self.remote_id]['audio']:
            audio_frame = rtc_io[self.call_id][self.remote_id]['audio'].pop(0)
            return audio_frame
        else:
            return self.default_frame


class VideoRemoteTrack(VideoStreamTrack):
    def __init__(self, call_id, remote_id):
        self.last = None
        self.call_id = call_id
        self.remote_id = remote_id
        self.default_frame = VideoFrame(width=640, height=480)

    async def recv(self):
        self.last = await pause(self.last, 0.05)
        if int(self.remote_id) == 2:
            print('2:   ', rtc_io[self.call_id][self.remote_id]['video'])
        if rtc_io[self.call_id][self.remote_id]['video']:
            self.default_frame = video_frame = rtc_io[self.call_id][self.remote_id]['video'].pop(0)
            return video_frame
        else:
            return self.default_frame


class VideoDummyTrack(VideoStreamTrack):
    def __init__(self):
        width = 640
        height = 480

        self.counter = 0
        self.frame_green = VideoFrame(width=width, height=height)
        self.frame_remote = VideoFrame(width=width, height=height)
        self.last = None

    async def recv(self):
        self.last = await pause(self.last, 0.04)
        self.counter += 1
        if (self.counter % 100) < 50:
            return self.frame_green
        else:
            return self.frame_remote


async def consume_audio(track, call_id, local_id, remote_id):
    
    while True:
        await asyncio.sleep(0.02)
        frame = await track.recv()
        if rtc_io[call_id][remote_id]["connected"]:
            rtc_io[call_id][local_id]['audio'].append(frame)


async def consume_video(track, call_id, local_id, remote_id):
    if rtc_io[call_id][remote_id]["connected"]:
        while True:
            rtc_io[call_id][local_id]['video'].append(await track.recv())


async def consume_video2(track, local_video):
    """
    Drain incoming video, and echo it back.
    """
    while True:
        local_video.frame_remote = await track.recv()


async def index(request):
    html = open(os.path.join(ROOT, 'index.html'), 'r').read()
    return web.Response(content_type='text/html', text=html)


async def offer(request):
    data = await request.json()
    offer = data['offer']
    offer = RTCSessionDescription(
        sdp=offer['sdp'],
        type=offer['type'])

    pc = RTCPeerConnection()
    pc._consumers = []
    pcs.append(pc)

    local_id = data['local_id']
    call_dict = rtc_io[data['call_id']]
    remote_id = [k for k in call_dict.keys() if k != local_id][0]
    call_dict[local_id]["connected"] = True
    # there is only two keys in call_dict and we want the other key

    remote_audio = AudioRemoteTrack(data['call_id'], remote_id)
    remote_video = VideoRemoteTrack(data['call_id'], remote_id)

    @pc.on('datachannel')
    def on_datachannel(channel):
        @channel.on('message')
        def on_message(message):
            channel.send('pong')

    @pc.on('track')
    def on_track(track):
        if track.kind == 'audio':
            pc.addTrack(remote_audio)
            pc._consumers.append(asyncio.ensure_future(consume_audio(track, data['call_id'], local_id, remote_id)))
        elif track.kind == 'video':
            pc.addTrack(remote_video)
            pc._consumers.append(asyncio.ensure_future(consume_video(track, data['call_id'], local_id, remote_id)))

    await pc.setRemoteDescription(offer)
    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    return web.Response(
        content_type='application/json',
        text=json.dumps({
            'sdp': pc.localDescription.sdp,
            'type': pc.localDescription.type
        }))


pcs = []


async def on_shutdown(app):
    # stop audio / video consumers
    for pc in pcs:
        for c in pc._consumers:
            c.cancel()

    # close peer connections
    coros = [pc.close() for pc in pcs]
    await asyncio.gather(*coros)


async def call(request):
    conn = psycopg2.connect(connect_str)
    cursor = conn.cursor()
    # call_id = str(md5(str(time.time())))
    call_inserted_id = 'call-1'
    caller_id = request.query['caller_id']
    callee_id = request.query['callee_id']

    rtc_io[call_inserted_id] = {}
    rtc_io[call_inserted_id][caller_id] = {
                                            'audio': [], 
                                            'video': [],
                                            'connected':False
                                        }
    rtc_io[call_inserted_id][callee_id] = {
                                            'audio': [], 
                                            'video': [],
                                            'connected':False
                                        }

    sql = f"""
          INSERT INTO calls (id,caller,callee,
                            type,start_time,status)
          VALUES ('{call_inserted_id}',{caller_id},{callee_id},2,{time.time()},1)
          returning id;
            """
    cursor.execute(sql)
    conn.commit()

    return web.Response(
        content_type='application/json',
        text=json.dumps({
            'call_id': call_inserted_id
        }))


async def call_answer(request):
    call_id = request.query["call_id"]
    status = request.query["status"]

    conn = psycopg2.connect(connect_str)
    cursor = conn.cursor()
    sql = f"""
          update calls
          set status = {status}
          where id = '{call_id}';
          """
    cursor.execute(sql)
    conn.commit()

    sql2 = f"""
            select caller 
            from calls
            where id = '{call_id}';
            """
    cursor.execute(sql2)
    res = cursor.fetchone()
    
    rtc_io[call_id][res[0]]["audio"] = []

    return web.Response(
        content_type='application/json',
        text=json.dumps({
            'status': 'success'
        }))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='WebRTC audio / video / data-channels demo')
    parser.add_argument('--port', type=int, default=8080,
                        help='Port for HTTP server (default: 8080)')
    parser.add_argument('--verbose', '-v', action='count')
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    app = web.Application()
    app.on_shutdown.append(on_shutdown)
    app.router.add_get('/call', call)
    app.router.add_get('/call_answer', call_answer)
    app.router.add_get('/', index)
    app.router.add_post('/offer', offer)
    web.run_app(app, port=args.port, host="0.0.0.0")

```

Thank you so much for your guidance

**Comment by jlaine** [comment]
That's a lot of code to read could you reduce it to a minimal test case? In particular, do you need the video streams to reproduce the issue?

**Comment by sogand145** [comment]
Yep, you`re right. maybe it was better I highlighted parts of the code.
please let me know why you`re using `pause` function?

```
async def pause(last, ptime):
    if last:
        now = time.time()
        await asyncio.sleep(last + ptime - now)
    return time.time()
```

the value returned from this line of code,  last + ptime - now, is always negative. I don`t know if it affects on getting frames (during writing & reading for both users).

But the major problem we have is that when we are going to connect two users by smart phone , we get this error on server.py:

```
Task exception was never retrieved
future: <Task finished coro=<RTCRtpSender._run() done, defined at /usr/local/lib/python3.6/site-packages/aiortc-0.5.0-py3.6-linux-x86_64.egg/aiortc/rtcrtpsender.py:78> exception=Exception('libvpx error: Invalid parameter',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiortc-0.5.0-py3.6-linux-x86_64.egg/aiortc/rtcrtpsender.py", line 89, in _run
    payloads = encoder.encode(frame)
  File "/usr/local/lib/python3.6/site-packages/aiortc-0.5.0-py3.6-linux-x86_64.egg/aiortc/codecs/vpx.py", line 193, in encode
    _vpx_assert(lib.vpx_codec_enc_config_set(self.codec, self.cfg))
  File "/usr/local/lib/python3.6/site-packages/aiortc-0.5.0-py3.6-linux-x86_64.egg/aiortc/codecs/vpx.py", line 116, in _vpx_assert
    raise Exception('libvpx error: ' + reason.decode('utf8'))
```
please tell me how to handle this error, what`s the reasonable codec for mobile phones?
and could you please tell me how to change resolution of frames during a call so that user with low internet bandwidth be able to use this call service?

**Comment by jlaine** [comment]
Hi Mahsa,

I'm happy to fix bugs in aiortc, but I can't afford to provide free support for debugging end-user code, so as I said previously a minimal test case illustrating one specific issue would be best. Your example seems to do audio, video, writing to a database..

Concerning audio delays: the "pause" function in the example was just provided because the audio was being read from a file, to avoid all audio getting sent at once. If you are using live sources you will need to rethink this logic as you already have a natural "pacing". You might consider using an asyncio.Queue for instance.

More fundamentally though : if you are just doing one-to-one conversations and are not applying any processing to the media streams, you probably don't need to use `aiortc` at all, all you need is a server to handle signaling. You can just let the users establish direct connections to each other, the peer-to-peer nature of WebRTC is one of its key features.

The error you are getting about vpx is probably due to mixing frames of different sizes (the hard-coded 640x480 frame and whatever you are receiving from the mobile device). Could you please check whether you get this error with the latest aiortc code on the *unmodified* server.py example? If so, please open a separate issue.
