### ISSUE TITLE
error in rtp.py

### ISSUE THREAD

**Issue by sogand145** [jlaine/aiortc#42]
Hi Jlaine,
Sometimes when I have audio & video call with another client, this error is occured on Terminal : 
```python
Task exception was never retrieved
future: <Task finished coro=<RTCRtpReceiver._run_rtcp() done, defined at /usr/local/lib/python3.6/site-packages/aiortc-0.9.1-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py:241> exception=error('argument out of range',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiortc-0.9.1-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 272, in _run_rtcp
    await self._send_rtcp(packet)
  File "/usr/local/lib/python3.6/site-packages/aiortc-0.9.1-py3.6-linux-x86_64.egg/aiortc/rtcrtpreceiver.py", line 280, in _send_rtcp
    await self.transport._send_rtp(bytes(packet))
  File "/usr/local/lib/python3.6/site-packages/aiortc-0.9.1-py3.6-linux-x86_64.egg/aiortc/rtp.py", line 175, in __bytes__
    payload += bytes(report)
  File "/usr/local/lib/python3.6/site-packages/aiortc-0.9.1-py3.6-linux-x86_64.egg/aiortc/rtp.py", line 74, in __bytes__
    self.jitter, self.lsr, self.dlsr)
struct.error: argument out of range
```
it seems it is related to rtp.py, please let me know what is it and how to fix it?
Thanks in advance

**Comment by jlaine** [comment]
This most likely means one of the following is negative:

- ssrc
- lost
- highest_sequence
- jitter
- lsr
- dlsr

Could you add some print() statements in rtp.py and report back which value is causing the problem?

**Comment by sogand145** [comment]
Yep, you`re right. I put some print statements in this section of code:
```python
def __bytes__(self):
        print("fraction_lost: ",self.fraction_lost)
        print("packets_lost: ",self.packets_lost)
        lost = (self.fraction_lost << 24) | self.packets_lost
        print("lost: ",lost)
        print("ssrc: ",self.ssrc)
        print("highest_sequence: ",self.highest_sequence)
        print("jitter: ",self.jitter)
        print("lsr: ",self.lsr)
        print("dlsr: ",self.dlsr)
        print("************************")
        return pack('!LLLLLL', self.ssrc, lost, self.highest_sequence,
                    self.jitter, self.lsr, self.dlsr)
```

It seems two values are negative:
```python
fraction_lost:  0
packets_lost:  -1
lost:  -1
ssrc:  3093796496
highest_sequence:  1817
jitter:  597
lsr:  1895013633
dlsr:  62253
```

**Comment by jlaine** [comment]
OK so it looks like there is something wrong in the packet loss calculation in StreamStatistics. Could you dump the sequence numbers of all received RTP packets, by adding this at the very beginning of `RTCRtpReceiver._handle_rtp_packet ` and posting the *full* output to a gist:

```python
print(packet.payload_type, packet.sequence_number)
```

**Comment by sogand145** [comment]
This is an output of print lines:
[output.txt](https://github.com/jlaine/aiortc/files/2223646/output.txt)

**Comment by sogand145** [comment]
Cool, It seems everything is great. Thank you so much
