### ISSUE TITLE
example videostream-cli not work

### ISSUE THREAD

**Issue by zhangguangfengz** [jlaine/aiortc#45]
I run the example 
python3 cli.py offer 
python3 cli.py answer
but met some error:

```
Sending video for 10s
Task exception was never retrieved
future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py:442> exception=Exception('libvpx error: ABI version mismatch',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 450, in __connect
    await transceiver.receiver.receive(self.__remoteRtp[transceiver])
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcrtpreceiver.py", line 140, in receive
    self.__decoders[codec.payloadType] = get_decoder(codec)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/__init__.py", line 29, in get_decoder
    return VpxDecoder()
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/vpx.py", line 133, in __init__
    _vpx_assert(lib.vpx_codec_dec_init(self.codec, lib.vpx_codec_vp8_dx(), ffi.NULL, 0))
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/vpx.py", line 127, in _vpx_assert
    raise Exception('libvpx error: ' + reason.decode('utf8'))
Exception: libvpx error: ABI version mismatch
Task exception was never retrieved
future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py:442> exception=Exception('libvpx error: ABI version mismatch',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 450, in __connect
    await transceiver.receiver.receive(self.__remoteRtp[transceiver])
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcrtpreceiver.py", line 140, in receive
    self.__decoders[codec.payloadType] = get_decoder(codec)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/__init__.py", line 29, in get_decoder
    return VpxDecoder()
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/vpx.py", line 133, in __init__
    _vpx_assert(lib.vpx_codec_dec_init(self.codec, lib.vpx_codec_vp8_dx(), ffi.NULL, 0))
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/vpx.py", line 127, in _vpx_assert
    raise Exception('libvpx error: ' + reason.decode('utf8'))
Exception: libvpx error: ABI version mismatch
Task exception was never retrieved
future: <Task finished coro=<RTCRtpSender._run_rtp() done, defined at /usr/local/lib/python3.5/dist-packages/aiortc/rtcrtpsender.py:94> exception=Exception('libvpx error: ABI version mismatch',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcrtpsender.py", line 106, in _run_rtp
    payloads = await loop.run_in_executor(None, encoder.encode, frame)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/vpx.py", line 226, in encode
    _vpx_assert(lib.vpx_codec_enc_init(self.codec, self.cx, self.cfg, 0))
  File "/usr/local/lib/python3.5/dist-packages/aiortc/codecs/vpx.py", line 127, in _vpx_assert
    raise Exception('libvpx error: ' + reason.decode('utf8'))
```

could you give me some advices?
I am using ubuntu 16.04.

**Comment by jlaine** [comment]
This seem to be unrelated to any specific example, there seems to be a problem on your machine : the libvpx used while compiling and while running seem to be different. Could you check you have just a single version if libvpx installed, and re-install aiortc?

**Comment by zhangguangfengz** [comment]
@jlaine 
Thank you ,jlaine.
The solution is very effective , the problem has solved.But I got another problem:
-------------------------------------------------------------------------------------------------------------------------------------------
Receiving video, press CTRL-C to stop
Exception in callback Task._wakeup(<Future finis...tionTimeout()>)
handle: <Handle Task._wakeup(<Future finis...tionTimeout()>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aioice/ice.py", line 751, in query_consent
    retransmissions=0)
  File "/usr/local/lib/python3.5/dist-packages/aioice/ice.py", line 194, in request
    return await transaction.run()
  File "/usr/local/lib/python3.5/dist-packages/aioice/stun.py", line 250, in run
    return await self.__future
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
aioice.exceptions.TransactionTimeout: STUN transaction timed out
-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by jlaine** [comment]
That's probably because the "answer" side never exited, so eventually STUN content to send expires (as the remote party is gone). I have made the example exit if we don't receive any video for 5s, so it should shut down cleanly see 854506cd7fe32091be863f722466fb6abf349929

I'm closing this issue, please open distinct issues for any other problems.

**Comment by zhangguangfengz** [comment]
@jlaine 
 Thank you,jlaine.That's really helpful.
