### ISSUE TITLE
One-way media stream using modified server example

### ISSUE THREAD

**Issue by eufat** [jlaine/aiortc#57]
I am trying to stream RTSP video to the client. In my case, I do not want the client to send its webcam video to the server, only the server that sends the video. I publish the code here:

https://github.com/eufat/nodeflux-aiortc/blob/master/server.py

My current idea is to asynchronously call the pc.addTrack to send the RTSP video provided with VideoFileTrack. I have an issue whenever addTrack is called, this error thrown:

```bash
Traceback (most recent call last):
  File "server.py", line 159, in <module>
    web.run_app(app, port=args.port, host='127.0.0.1')
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 472, in run_app
    loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "server.py", line 102, in handler
    roll_video()
  File "server.py", line 91, in roll_video
    pc.addTrack(local_video)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 205, in addTrack
    transceiver = self.__createTransceiver(kind=track.kind, sender_track=track)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 561, in __createTransceiver
    dtlsTransport = self.__createDtlsTransport()
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 488, in __createDtlsTransport
    self.__iceTransports.add(iceTransport)
AttributeError: 'list' object has no attribute 'add'
```

To reproduce this issue, you can clone the repo [https://github.com/eufat/nodeflux-aiortc](here) and start the server by running `python server.py`

**Comment by jlaine** [comment]
There was a bug in the way unused transports were discarded, it should now be fixed on master.

I didn't check whether your code does what you expect it to, but it now longer bombs.
