### ISSUE TITLE
Error while running server.py in example/server

### ISSUE THREAD

**Issue by mdv3101** [jlaine/aiortc#71]
When i try to run the server.py file, i got the following error.
`python server.py 
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/aiortc/__init__.py", line 11, in <module>
    from .rtcpeerconnection import RTCPeerConnection  # noqa
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 8, in <module>
    from .codecs import MEDIA_CODECS
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/aiortc/codecs/__init__.py", line 5, in <module>
    from .h264 import H264Decoder, H264Encoder, h264_depayload
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/aiortc/codecs/h264.py", line 7, in <module>
    import av
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/av/__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/av/audio/__init__.py", line 1, in <module>
    from .frame import AudioFrame
  File "av/audio/frame.pyx", line 1, in init av.audio.frame
  File "av/codec/codec.pxd", line 6, in init av.frame
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/av/codec/__init__.py", line 1, in <module>
    from .codec import Codec, codecs_available, codec_descriptor
  File "av/video/format.pxd", line 4, in init av.codec.codec
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/av/video/__init__.py", line 1, in <module>
    from .frame import VideoFrame
  File "av/container/streams.pxd", line 4, in init av.video.frame
  File "/home/madhav/anaconda3/lib/python3.6/site-packages/av/container/__init__.py", line 1, in <module>
    from .core import Container, open
  File "av/container/output.pxd", line 8, in init av.container.core
ImportError: /home/madhav/anaconda3/lib/python3.6/site-packages/av/container/output.cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_packet_clone`

The ffmpeg version is 4.0 in my system.

**Comment by jlaine** [comment]
For some reason your ffmpeg 4.0 is not the one being picked up at runtime, `av_packet_clone` being missing a reliable indicator that ffmpeg < 3 is the one being used. You could try running the following to see what libav* libraries are being picked up:

`ldd /home/madhav/anaconda3/lib/python3.6/site-packages/av/container/output.cpython-36m-x86_64-linux-gnu.so`

**Comment by mdv3101** [comment]
I am getting this:
`python-36m-x86_64-linux-gnu.so | grep libav
	libavutil-ffmpeg.so.54 => /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 (0x00007f176a9b3000)
	libavformat-ffmpeg.so.56 => /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 (0x00007f176a5b4000)
	libavdevice-ffmpeg.so.56 => /usr/lib/x86_64-linux-gnu/libavdevice-ffmpeg.so.56 (0x00007f176a386000)
	libavcodec-ffmpeg.so.56 => /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 (0x00007f1768f55000)
	libavfilter-ffmpeg.so.5 => /usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5 (0x00007f1768923000)
	libavc1394.so.0 => /usr/lib/x86_64-linux-gnu/libavc1394.so.0 (0x00007f1763b18000)
	libavresample-ffmpeg.so.2 => /usr/lib/x86_64-linux-gnu/libavresample-ffmpeg.so.2 (0x00007f175f10c000)`

**Comment by jlaine** [comment]
The versions you included in your ldd output correspond to ffmpeg 2.8.15, that seems to be what you have installed with your package manager.

Your ffmpeg 4.0 in a non-standard location, which means at the very least your are going to have to set the LD_LIBRARY_PATH environment variable to point to where this ffmpeg's .so files live, otherwise your OS's dynamic linker has zero chance of picking them up. You might even have to rebuild PyAV.
