### ISSUE TITLE
running aoirtc in gpu

### ISSUE THREAD

**Issue by blinkbink** [jlaine/aiortc#73]
using:
-python 3.5
-aiortc 0.9.8
i'm using python3 to running, but i run the process in gpu on cloud nvidia, on local i run with python3 too but without gpu thats work. i run like this on cloud:
`python3 server.py`
got error this:
```
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack
  File "/usr/local/lib/python3.5/dist-packages/aiortc-0.9.8-py3.5-linux-x86_64.egg/aiortc/__init__.py", line 11, in <module>
    from .rtcpeerconnection import RTCPeerConnection  # noqa
  File "/usr/local/lib/python3.5/dist-packages/aiortc-0.9.8-py3.5-linux-x86_64.egg/aiortc/rtcpeerconnection.py", line 8, in <module>
    from .codecs import MEDIA_CODECS
  File "/usr/local/lib/python3.5/dist-packages/aiortc-0.9.8-py3.5-linux-x86_64.egg/aiortc/codecs/__init__.py", line 5, in <module>
    from .h264 import H264Decoder, H264Encoder, h264_depayload
  File "/usr/local/lib/python3.5/dist-packages/aiortc-0.9.8-py3.5-linux-x86_64.egg/aiortc/codecs/h264.py", line 7, in <module>
    import av
  File "/usr/local/lib/python3.5/dist-packages/av-0.5.2-py3.5-linux-x86_64.egg/av/__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "/usr/local/lib/python3.5/dist-packages/av-0.5.2-py3.5-linux-x86_64.egg/av/audio/__init__.py", line 1, in <module>
    from .frame import AudioFrame
  File "av/audio/frame.pyx", line 1, in init av.audio.frame
  File "av/codec/codec.pxd", line 6, in init av.frame
  File "/usr/local/lib/python3.5/dist-packages/av-0.5.2-py3.5-linux-x86_64.egg/av/codec/__init__.py", line 1, in <module>
    from .codec import Codec, codecs_available, codec_descriptor
  File "av/video/format.pxd", line 4, in init av.codec.codec
  File "/usr/local/lib/python3.5/dist-packages/av-0.5.2-py3.5-linux-x86_64.egg/av/video/__init__.py", line 1, in <module>
    from .frame import VideoFrame
  File "av/container/streams.pxd", line 4, in init av.video.frame
  File "/usr/local/lib/python3.5/dist-packages/av-0.5.2-py3.5-linux-x86_64.egg/av/container/__init__.py", line 1, in <module>
    from .core import Container, open
  File "av/container/output.pxd", line 8, in init av.container.core
ImportError: /usr/local/lib/python3.5/dist-packages/av-0.5.2-py3.5-linux-x86_64.egg/av/container/output.cpython-35m-x86_64-linux-gnu.so: undefined symbol: av_packet_clone

```
any clue ?

**Comment by jlaine** [comment]
You need ffmpeg 3.0 or better
