### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sendto'

### ISSUE THREAD

**Issue by dsvictor94** [jlaine/aiortc#85]
Hi,

I am receiving the error `AttributeError: 'NoneType' object has no attribute 'sendto'` In the interns of aiortc. 
It is am intermittent error  happen approximately in 1/5 of the connections
Any tip to fiz this?  

below the trackback and in this gist (https://gist.github.com/dsvictor94/19c2e8a9589cb0afd7906c0644940f6e) the full log in debug mode

```
ERROR: Task exception was never retrieved
future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aiortc/rtcpeerconnection.py:554> exception=AttributeError("'NoneType' object has no attribute 'call_exception_handler'",)>
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/selector_events.py", line 1102, in sendto
    self._sock.sendto(data, addr)
AttributeError: 'NoneType' object has no attribute 'sendto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aiortc/rtcpeerconnection.py", line 561, in __connect
    await dtlsTransport.start(self.__remoteDtls[transceiver])
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aiortc/rtcdtlstransport.py", line 325, in start
    await self._recv_next()
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aiortc/rtcdtlstransport.py", line 476, in _recv_next
    await self._write_ssl()
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aiortc/rtcdtlstransport.py", line 549, in _write_ssl
    await self.transport._send(ffi.buffer(self.write_cdata)[0:result])
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aiortc/rtcicetransport.py", line 313, in _send
    await self._connection.send(data)
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aioice/ice.py", line 449, in send
    await self.sendto(data, 1)
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aioice/ice.py", line 459, in sendto
    await active_pair.protocol.send_data(data, active_pair.remote_addr)
  File "/home/victor/.pyenv/versions/3.5.3/envs/fx_webrtc/lib/python3.5/site-packages/aioice/ice.py", line 193, in send_data
    self.transport.sendto(data, addr)
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/selector_events.py", line 1111, in sendto
    'Fatal write error on datagram transport')
  File "/home/victor/.pyenv/versions/3.5.3/lib/python3.5/asyncio/selector_events.py", line 639, in _fatal_error
    self._loop.call_exception_handler({
AttributeError: 'NoneType' object has no attribute 'call_exception_handler'
```

I will try produce a minimal exemple that reproduce the problem,

Thank You

**Comment by dsvictor94** [comment]
Maybe this helps diagnoses the problem:

This is all the code direct related with aiortc, The signaling occur over MQTT 
```
async def session(signaling):
    try:
        params = await signaling.connect()
        
        iceServers = [ RTCIceServer(**server) for server in params.get('iceServers', [])]

        pc = RTCPeerConnection(RTCConfiguration(iceServers=iceServers))

        track = VideoStreamTrack()
        pc.addTrack(track)

        @pc.on('track')
        def on_track(track):
            logger.info('Track %s received' % track.kind)
            MediaBlackhole().addTrack(track)

        await pc.setLocalDescription(await pc.createOffer())
        await signaling.send(pc.localDescription)

        # consume signaling
        while True:
            try:
                obj = await signaling.receive()
            except Close:
                logger.info('Exiting')
                break

            logger.debug('New objec from signaling: %s', obj)

            if isinstance(obj, RTCSessionDescription):
                await pc.setRemoteDescription(obj)

                if obj.type == 'offer':
                    await pc.setLocalDescription(await pc.createAnswer())
                    await signaling.send(pc.localDescription)
            elif isinstance(obj, RTCIceCandidate):
                pc.addIceCandidate(obj)
            else:
                logger.info('Exiting')
                break
    finally:
        await signaling.close()
        await pc.close()
```

**Comment by jlaine** [comment]
This looks more like an aioice issue

**Comment by jlaine** [comment]
Also a note: I'm not happy with MediaBlackhole and I'm considering removing it: it's inefficient to receive, decode then discard media. If you know you don't care about the received media, it's better to make the transceiver `"sendonly"`. I need to update the examples to reflect this.

**Comment by dsvictor94** [comment]
I did a more detailed debug I apparently the cause is because de MQTT (with qos 1) are delivering duplicate messages and it cause ` pc.setRemoteDescription(obj)` be called twice.

I will test deduplicate the messages, and update here soon

Thanks

**Comment by jlaine** [comment]
That's still weird as hell, the error seems so unrelated! If you have a snippet which can trigger this with dummy signaling I might want it for a testcase

**Comment by dsvictor94** [comment]
Confirmed, the erro cause by calling `pc.setRemoteDescription` twice.
I will modify some exemple to reproduce the exception and send here

**Comment by jlaine** [comment]
The weird thing is you shouldn't be able to call setRemoteDescription twice as it should advance the signaling, and we assert you are in an appropriate state to apply a remote description

**Comment by dsvictor94** [comment]
I changed the apprtc exemple to try replicate the error but as you mentioned the method `setRemoteDescription` fails nicely if it is called twice.

Reading the log again, in fact the `setRemoteDescription` is not called twice when the erro occurs. It would be, but the exception occurs before it.

Maybe the root cause is something weird happening in the python `selector` generated by others things that share the same event loop.
Feel free to close this issue until I proper diagnose if the cause is the aiortc.

**Comment by jlaine** [comment]
OK, feel free to re-open once we have the root cause identified
