### ISSUE TITLE
Segmentation fault (core dumped) running example

### ISSUE THREAD

**Issue by Novemser** [jlaine/aiortc#87]
I was trying to run
```bash
python server.py -v
```
in `example/server`, but got a segmentation fault after I opened my browser and started my webcam

```bash
➜  server git:(master) python server.py -v                                    
DEBUG:asyncio:Using selector: EpollSelector
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
INFO:aiohttp.access:192.168.13.116 [23/Oct/2018:10:27:35 +0000] "GET / HTTP/1.1" 200 2495 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
INFO:aiohttp.access:192.168.13.116 [23/Oct/2018:10:27:35 +0000] "GET /client.js HTTP/1.1" 200 7035 "http://192.168.11.23:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
DEBUG:ice:controlled - new -> closed
Track video received
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=12 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=13 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(2) connection_made(<_SelectorDatagramTransport fd=14 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(3) connection_made(<_SelectorDatagramTransport fd=15 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(4) connection_made(<_SelectorDatagramTransport fd=16 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(0) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x18\x8d\\b\x87.\xb4"K\x06\xa3K')
DEBUG:ice:Connection(0) protocol(3) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf3|\xa2\x86f8T\xaeQ\x81\x1a\xd6')
DEBUG:ice:Connection(0) protocol(4) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xbf\xe8\x94\xea\xdc\xaf\xbcR\xd1\x87-\xcb')
DEBUG:ice:Connection(0) protocol(2) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b']XMM\xc4by\x07\xea,\xcc\xeb')
DEBUG:ice:Connection(0) protocol(1) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b';\xf2\x14\xf5[\xd9\xd6l\xac\xf1\xe0\xa1')
DEBUG:ice:Connection(0) protocol(0) < ('64.233.188.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\x18\x8d\\b\x87.\xb4"K\x06\xa3K')
DEBUG:ice:Connection(0) protocol(2) < ('64.233.188.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b']XMM\xc4by\x07\xea,\xcc\xeb')
DEBUG:ice:Connection(0) protocol(1) < ('64.233.188.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b';\xf2\x14\xf5[\xd9\xd6l\xac\xf1\xe0\xa1')
DEBUG:ice:Connection(0) protocol(3) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf3|\xa2\x86f8T\xaeQ\x81\x1a\xd6')
DEBUG:ice:Connection(0) protocol(4) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xbf\xe8\x94\xea\xdc\xaf\xbcR\xd1\x87-\xcb')
DEBUG:ice:Connection(0) protocol(3) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf3|\xa2\x86f8T\xaeQ\x81\x1a\xd6')
DEBUG:ice:Connection(0) protocol(4) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xbf\xe8\x94\xea\xdc\xaf\xbcR\xd1\x87-\xcb')
DEBUG:ice:Connection(0) protocol(3) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf3|\xa2\x86f8T\xaeQ\x81\x1a\xd6')
DEBUG:ice:Connection(0) protocol(4) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xbf\xe8\x94\xea\xdc\xaf\xbcR\xd1\x87-\xcb')
INFO:aiohttp.access:192.168.13.116 [23/Oct/2018:10:27:42 +0000] "POST /offer HTTP/1.1" 200 3019 "http://192.168.11.23:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
DEBUG:ice:controlled - new -> checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.11.23', 35513) -> ('192.168.13.116', 53667)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.18.0.1', 43195) -> ('192.168.13.116', 53667)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.17.0.1', 52594) -> ('192.168.13.116', 53667)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.16.236.1', 34106) -> ('192.168.13.116', 53667)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.16.245.1', 53313) -> ('192.168.13.116', 53667)) State.FROZEN -> State.WAITING
ICE connection state is checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.11.23', 35513) -> ('192.168.13.116', 53667)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'J\xc3\x16\xdb\x94%\xfa\xd3Wy\xfb\xca')
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xccr=\xcdj\x1c\xd0\x7f\x05\x0b3y')
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xccr=\xcdj\x1c\xd0\x7f\x05\x0b3y')
INFO:ice:Connection(0) Check CandidatePair(('172.18.0.1', 43195) -> ('192.168.13.116', 53667)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(1) > ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x8a\x12\xa3\xc5\x19A\xecX\x8c\x9ao5')
INFO:ice:Connection(0) Check CandidatePair(('172.17.0.1', 52594) -> ('192.168.13.116', 53667)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(2) > ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xa2\xa2\xf8yr\x18\x89\xca\x89\x18:Z')
INFO:ice:Connection(0) Check CandidatePair(('172.16.236.1', 34106) -> ('192.168.13.116', 53667)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(3) > ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b']Z\x15\xcc\xf5\x17y\xdfg\x8e\xeaY')
INFO:ice:Connection(0) Check CandidatePair(('172.16.245.1', 53313) -> ('192.168.13.116', 53667)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(4) > ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'6\xc03\x14X\xf5\x97\xdd\x15zd9')
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'J\xc3\x16\xdb\x94%\xfa\xd3Wy\xfb\xca')
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'J\xc3\x16\xdb\x94%\xfa\xd3Wy\xfb\xca')
INFO:ice:Connection(0) Check CandidatePair(('192.168.11.23', 35513) -> ('192.168.13.116', 53667)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) ICE completed
DEBUG:ice:controlled - checking -> completed
DEBUG:dtls:client - State.NEW -> State.CONNECTING
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) DATA 296
ICE connection state is completed
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 735
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) DATA 675
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 75
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 137
DEBUG:dtls:client - DTLS handshake complete
DEBUG:dtls:client - State.CONNECTING -> State.CONNECTED
DEBUG:sctp:server < InitChunk(flags=0)
DEBUG:sctp:server - Peer supports 256 outbound streams, 2048 max inbound streams
DEBUG:sctp:server > InitAckChunk(flags=0)
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) DATA 105
DEBUG:rtp:sender(video) - RTP started
DEBUG:rtp:sender(video) - RTCP started
DEBUG:rtp:receiver(video) - RTCP started
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 77
DEBUG:sctp:server < CookieEchoChunk(flags=0)
DEBUG:sctp:server > CookieAckChunk(flags=0)
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) DATA 53
DEBUG:sctp:server - State.CLOSED -> State.ESTABLISHED
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 81
DEBUG:sctp:server < DataChunk(flags=3, tsn=1581304408, stream_id=1, stream_seq=0)
DEBUG:datachannel:1 - connecting -> open
DEBUG:sctp:server > DataChunk(flags=3, tsn=3054058094, stream_id=1, stream_seq=0)
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) DATA 69
DEBUG:sctp:server - T3 start
DEBUG:sctp:server > SackChunk(flags=0, advertised_rwnd=131072, cumulative_tsn=1581304408, gaps=[])
DEBUG:ice:Connection(0) protocol(0) > ('192.168.13.116', 53667) DATA 65
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 65
DEBUG:sctp:server < SackChunk(flags=0, advertised_rwnd=131072, cumulative_tsn=3054058094, gaps=[])
DEBUG:sctp:server - T3 cancel
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 94
DEBUG:rtp:receiver(video) < RtcpSrPacket(ssrc=4023777495, sender_info=RtcpSenderInfo(ntp_timestamp=16103031833741139265, rtp_timestamp=1579969357, packet_count=0, octet_count=0), reports=[])
DEBUG:rtp:receiver(video) < RtcpSdesPacket(chunks=[RtcpSourceInfo(ssrc=4023777495, items=[(1, b'{283537ed-7dfb-46e2-b9cd-6c7aea3f7a4f}')])])
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 65
DEBUG:rtp:receiver(video) < RtpPacket(seq=21753, ts=1579969357, marker=0, payload=126, 23 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21754, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21755, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21756, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21757, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21758, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21759, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21760, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1130
DEBUG:rtp:receiver(video) < RtpPacket(seq=21761, ts=1579969357, marker=0, payload=126, 1088 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 1127
DEBUG:rtp:receiver(video) < RtpPacket(seq=21762, ts=1579969357, marker=1, payload=126, 1085 bytes)
DEBUG:ice:Connection(0) protocol(0) < ('192.168.13.116', 53667) DATA 778
DEBUG:rtp:receiver(video) < RtpPacket(seq=21763, ts=1579974307, marker=1, payload=126, 736 bytes)
[1]    26969 segmentation fault (core dumped)  python server.py -v

```

**Comment by Novemser** [comment]
The above problem only occurs when I choose `H264/90000`.
![image](https://user-images.githubusercontent.com/12718118/47354824-4dc53680-d6f2-11e8-9a56-0b32dd7a852e.png)

**Comment by jlaine** [comment]
What version of PyAV do you have? Ensure it's 6.0.0 and let me know if the segfault still occurs.

If it does occur, you're going to at the very least provide a gdb backtrace otherwise there is no chance of debugging this.

**Comment by Novemser** [comment]
```bash
➜  server git:(master) python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import av
>>> av.__version__
'6.0.0'
```
gdb info(I'm new to gdb, don't know whether these logs could help locate the problem)
```bash
Thread 17 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb86c0700 (LWP 16777)]
0x00000000000f4240 in ?? ()
(gdb) bt
#0  0x00000000000f4240 in ?? ()
#1  0x00007fffe00f1887 in ?? () from /home/novemser/anaconda3/lib/python3.6/site-packages/../.././libavcodec.so.58
#2  0x00007fffe00e5a43 in ?? () from /home/novemser/anaconda3/lib/python3.6/site-packages/../.././libavcodec.so.58
#3  0x00007fffe00e9b03 in ?? () from /home/novemser/anaconda3/lib/python3.6/site-packages/../.././libavcodec.so.58
#4  0x00007fffe00eb090 in ?? () from /home/novemser/anaconda3/lib/python3.6/site-packages/../.././libavcodec.so.58
#5  0x00007fffe00f151f in ?? () from /home/novemser/anaconda3/lib/python3.6/site-packages/../.././libavcodec.so.58
#6  0x00007fffdffca577 in ?? () from /home/novemser/anaconda3/lib/python3.6/site-packages/../.././libavcodec.so.58
#7  0x00007fffdffcd208 in avcodec_send_packet () from /home/novemser/anaconda3/lib/python3.6/site-packages/../.././libavcodec.so.58
#8  0x00007fffcc647989 in __pyx_f_2av_5codec_7context_12CodecContext__send_packet_and_recv (__pyx_v_self=0x7fffc7874678, __pyx_v_packet=0x7fffc781e4a8)
    at src/av/codec/context.c:5325
#9  0x00007fffcc646fcb in __pyx_f_2av_5codec_7context_12CodecContext_decode (__pyx_v_self=0x7fffc7874678, __pyx_skip_dispatch=<optimized out>, 
    __pyx_optional_args=<optimized out>) at src/av/codec/context.c:6697
#10 0x00007fffcc641ed0 in __pyx_pf_2av_5codec_7context_12CodecContext_16decode (__pyx_v_packet=0x7fffc781e4a8, __pyx_v_self=0x7fffc7874678)
    at src/av/codec/context.c:6901
#11 __pyx_pw_2av_5codec_7context_12CodecContext_17decode (__pyx_v_self=0x7fffc7874678, __pyx_args=<optimized out>, __pyx_kwds=<optimized out>)
    at src/av/codec/context.c:6881
#12 0x00005555556639e4 in _PyCFunction_FastCallDict ()
#13 0x00005555556f0dfc in call_function ()
#14 0x000055555571594a in _PyEval_EvalFrameDefault ()
#15 0x00005555556eaf8b in fast_function ()
#16 0x00005555556f0ed5 in call_function ()
#17 0x000055555571594a in _PyEval_EvalFrameDefault ()
#18 0x00005555556ebcb9 in PyEval_EvalCodeEx ()
#19 0x00005555556ecbd6 in function_call ()
#20 0x00005555556637ee in PyObject_Call ()
#21 0x000055555571710b in _PyEval_EvalFrameDefault ()
#22 0x00005555556eaf8b in fast_function ()
#23 0x00005555556f0ed5 in call_function ()
#24 0x000055555571594a in _PyEval_EvalFrameDefault ()
#25 0x00005555556eaf8b in fast_function ()
#26 0x00005555556f0ed5 in call_function ()
#27 0x000055555571594a in _PyEval_EvalFrameDefault ()
#28 0x00005555556eb5db in _PyFunction_FastCallDict ()
#29 0x0000555555663daf in _PyObject_FastCallDict ()
#30 0x0000555555668a73 in _PyObject_Call_Prepend ()
#31 0x00005555556637ee in PyObject_Call ()
#32 0x0000555555762526 in t_bootstrap ()
#33 0x00007ffff7bbd6db in start_thread (arg=0x7fffb86c0700) at pthread_create.c:463
#34 0x00007ffff78e688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by jlaine** [comment]
Hm, the issue *might* be in PyAV itself, but I'm not sure how to move forward on this.

**Comment by jlaine** [comment]
I haven't had any luck reproducing this crash. I have tried Python 3.6 / 3.7 combined with PyAV 6.0 / 6.1, using FFmpeg 4.0.x. Do you get the crash systematically?
