### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by blinkbink** [jlaine/aiortc#93]
hello, i'm update from 9.8 to 9.12, but i got error on aiortc 9.12 like this:
> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "server.py", line 109, in offer
    await pc.setRemoteDescription(offer)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.12-py3.6-linux-x86_64.egg/aiortc/rtcpeerconnection.py", line 468, in setRemoteDescription
    add_remote_candidates(iceTransport, media)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.12-py3.6-linux-x86_64.egg/aiortc/rtcpeerconnection.py", line 93, in add_remote_candidates
    iceTransport.addRemoteCandidate(candidate)
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.12-py3.6-linux-x86_64.egg/aiortc/rtcicetransport.py", line 256, in addRemoteCandidate
    self._connection.add_remote_candidate(candidate_to_aioice(candidate))
  File "/usr/local/lib/python3.6/dist-packages/aiortc-0.9.12-py3.6-linux-x86_64.egg/aiortc/rtcicetransport.py", line 60, in candidate_to_aioice
    type=x.type)
TypeError: __init__() got an unexpected keyword argument 'related_address'

all code is default from github without edited, how to fix it ?

**Comment by jlaine** [comment]
Your `aioice` version seems to be too old, it should be 0.6.9 or higher to support `aiortc` 0.9.12:

https://github.com/jlaine/aiortc/blob/1c39af0c7a0d012047dc75292f302ab0bfd69a56/setup.py#L15
